#+SETUPFILE: setup.org
#+TITLE: Homework 2

* Task 1 (20 pts)

Define a GPS-type problem. Give the goal condition, initial
conditions, and operations, where for each operation the action,
preconditions, "add" conditions, and "delete" conditions are defined.
At least five operators must be defined.

Then, list a sequence of actions (in the correct order) that solve the
problem. At least three operators must be used.

* Task 2 (20 pts)

Give the sequence of states visited in a hill-climbing search applied
to the [[./search-practice.html][Goodale routing problem]], starting
at Woodruff & Tuttle and ending at Goodale parking lot.

Note, list the states visited, not just the states in the final route.
There may (or may not) be some backtracking so the states visited may
differ from the ultimate route.

* Task 3 (20 pts)

Repeat task 2 but for A* search.

* Task 4 (5 pts)

The Goodale routing problem used road intersection distance to find
the routes (when informed search was used). However, this distance
("as the crow flies") is only one aspect of what makes one route
better than another. What other information should we use to find the
truly minimal-time route between these two locations?

* Task 5 (5 pts)

What are some /admissible/ heuristics for the 8-puzzle problem? Give
at least two.

* Task 6 (15 pts)

Define breadth-first search in terms of the cost function $f(s) = g(s) + h(s)$
where $g(s)$ is the cost of arriving at state $s$ and $h(s)$
is the (estimated) cost of getting from $s$ to the goal state. That is
to say, give simple definitions for $g(s)$ and $h(s)$ so that the
[[./informed-search.html#sec-6][A search algorithm]] acts like
breadth-first search.

Also define depth-first search in terms of $f(s) = g(s) + h(s)$.

* Task 7 (15 pts)

Show a graph of minimax operation for this tic-tac-toe board, where
'x' is to make a move (and 'o' is the opponent). The graph should look
similar to those in the [[./adversarial-search.html][adversarial
search]] notes.

#+BEGIN_HTML
<table class="full">
<tr>
<td>x</td><td>o</td><td>x</td>
</tr>
<tr>
<td></td><td></td><td>x</td>
</tr>
<tr>
<td>x</td><td>o</td><td>o</td>
</tr>
</table>
#+END_HTML


#+INCLUDE: footer.org
